[tool.poetry]
name = "price-tracker"
version = "0.1.0"
description = ""
authors = ["jvc19"]
readme = "README.md"
packages = [{include = "price_tracker"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
